[workspace]
members = [
# <<<<<<< HEAD
  "rust", 
  "python",
  # "mbn_c",
# =======
#   "mbn", 
#   "mbn_c",
#   "mbn_python",
# >>>>>>> 0cce253 (ADD: Added mbn_c with base functionality.)
]
resolver = "2"

[workspace.dependencies]
pyo3 = "0.23.5"
pyo3-build-config = "0.23.5"
